import imageio
import torchvision
from utils import metrics
to_tensor = torchvision.transforms.ToTensor()

imgv1 = imageio.v3.imread(r'../results/images/SAR/Synthesis_no_log_SAR/v14_v1/nor_test_output.tif')
imgv4 = imageio.v3.imread(r'../results/images/SAR/Synthesis_no_log_SAR/v17_v4/20210919_756_output.tif')
imgv7 = imageio.v3.imread(r'../results/images/SAR/Synthesis_no_log_SAR/v18_v7/test_output.tif')
imgv11 = imageio.v3.imread(r'../results/images/SAR/Synthesis_no_log_SAR/v19_v11/20210919_756_output.tif')
noisy1 = imageio.v3.imread(r'../scratch/data/synthesis_v1/int_test/test.tif')
# print(metrics.compute_enl(imgv1[340:370, 405:425]))
imgcamUC1 = imageio.v3.imread(r'E:\SAR-CAM\data\nor_test\nor_tes_UC_output.tif')
imgcamS2 = imageio.v3.imread(r'E:\SAR-CAM\data\int_test\test_UC_output.tif')
# print(metrics.compute_enl(imgcam[340:370, 405:425]))
imgtrans1 = imageio.v3.imread(r'E:\sar_transformer\int_test\test_output.tif')
imgtransUC1 = imageio.v3.imread(r'E:\sar_transformer\int_test\test_UC_output.tif')
imgon1 = imageio.v3.imread(r'E:\sar_overcomplete\int_test\test_output.tif')
imgonUC1 = imageio.v3.imread(r'E:\sar_overcomplete\int_test\test_UC_output.tif')
# print(metrics.compute_enl(imgtrans[340:370, 405:425]))
#imgtrans1 = (imgtrans1 / 255.0).astype(np.float32)


imgv1 =to_tensor(imgv1[321:329, 165:172]).unsqueeze(0)
imgv4 =to_tensor(imgv4[321:329, 165:172]).unsqueeze(0)
imgv7 =to_tensor(imgv7[321:329, 165:172]).unsqueeze(0)
imgv11 =to_tensor(imgv11[321:329, 165:172]).unsqueeze(0)
noisy1 = to_tensor(noisy1[321:329, 165:172]).unsqueeze(0)
imgcamUC1 =to_tensor(imgcamUC1[321:329, 165:172]).unsqueeze(0)
imgcamS2 =to_tensor(imgcamS2[321:329, 165:172]).unsqueeze(0)
imgtrans1 =to_tensor(imgtrans1[321:329, 165:172]).unsqueeze(0)
imgtransUC1 =to_tensor(imgtransUC1[321:329, 165:172]).unsqueeze(0)
imgon1 =to_tensor(imgon1[321:329, 165:172]).unsqueeze(0)
imgonUC1 =to_tensor(imgonUC1[321:329, 165:172]).unsqueeze(0)

enlv1 = metrics.compute_enl(imgv1)
enlv4 = metrics.compute_enl(imgv4)
enlv7 = metrics.compute_enl(imgv7)
enlv11 = metrics.compute_enl(imgv11)
moiv1 = metrics.calculate_MoI(imgv1, noisy1)
moiv4 = metrics.calculate_MoI(imgv4, noisy1)
moiv7 = metrics.calculate_MoI(imgv7, noisy1)
moiv11 = metrics.calculate_MoI(imgv11, noisy1)
Cxv1 = metrics.calculate_Cx(imgv1)
Cxv4 = metrics.calculate_Cx(imgv4)
Cxv7 = metrics.calculate_Cx(imgv7)
Cxv11 = metrics.calculate_Cx(imgv11)

enlcam = metrics.compute_enl(imgcamUC1)
moicam = metrics.calculate_MoI(imgcamUC1, noisy1)
Cxcam = metrics.calculate_Cx(imgcamUC1)

enlcamS2 = metrics.compute_enl(imgcamS2)
moicamS2 = metrics.calculate_MoI(imgcamS2, noisy1)
CxcamS2 = metrics.calculate_Cx(imgcamS2)

enltrans = metrics.compute_enl(imgtrans1)
moitrans = metrics.calculate_MoI(imgtrans1, noisy1)
Cxtrans = metrics.calculate_Cx(imgtrans1)

enltransUC = metrics.compute_enl(imgtransUC1)
moitransUC = metrics.calculate_MoI(imgtransUC1, noisy1)
CxtransUC = metrics.calculate_Cx(imgtransUC1)

enlon = metrics.compute_enl(imgon1)
moion = metrics.calculate_MoI(imgon1, noisy1)
Cxon = metrics.calculate_Cx(imgon1)

enlonUC = metrics.compute_enl(imgonUC1)
moionUC = metrics.calculate_MoI(imgonUC1, noisy1)
CxonUC = metrics.calculate_Cx(imgonUC1)

print('20210919_844')
print('ENLv1:', enlv1)
print('ENLv4:', enlv4)
print('ENLv7:', enlv7)
print('ENLv11:', enlv11)
print('ENLcamUC:', enlcam)
print('ENLcamS2:', enlcamS2)
print('ENLtrans:', enltrans)
print('ENLtransUC:', enltransUC)
print('ENLon:', enlon)
print('ENLonUC:', enlonUC)

print('MOIv1:', moiv1)
print('MOIv4:', moiv4)
print('MOIv7:', moiv7)
print('MOIv11:', moiv11)
print('MOIcamUC:', moicam)
print('MOIcamS2:', moicamS2)
print('MOItrans:', moitrans)
print('MOItransUC:', moitransUC)
print('MOIon:', moion)
print('MOIonUC:', moionUC)

print('Cxv1:', Cxv1)
print('Cxv4:', Cxv4)
print('Cxv7:', Cxv7)
print('Cxv11:', Cxv11)
print('CxcamUC:', Cxcam)
print('CxcamS2:', CxcamS2)
print('Cxtrans:', Cxtrans)
print('CxtransUC:', CxtransUC)
print('Cxon:', Cxon)
print('CxonUC:', CxonUC)